import type { CauLacBo, DonDangKy, LichSuThaoTac } from './types';

export const DEFAULT_CAU_LAC_BO: CauLacBo[] = [
	{
		id: 'clb-01',
		anhDaiDien: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=300&q=80',
		tenCauLacBo: 'CLB Lập Trình Web',
		ngayThanhLap: '12/09/2023',
		moTa: '<p>CLB tập trung vào <strong>React</strong>, <strong>TypeScript</strong>, UmiJS và quy trình làm việc nhóm theo dự án thật.</p>',
		chuNhiem: 'Nguyễn Minh Anh',
		hoatDong: true,
	},
	{
		id: 'clb-02',
		anhDaiDien: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=300&q=80',
		tenCauLacBo: 'CLB Truyền Thông Sáng Tạo',
		ngayThanhLap: '18/03/2022',
		moTa: '<p>CLB chuyên thiết kế ấn phẩm, sản xuất nội dung số, truyền thông sự kiện và hỗ trợ nhận diện hình ảnh cho khoa.</p>',
		chuNhiem: 'Trần Thu Hà',
		hoatDong: true,
	},
	{
		id: 'clb-03',
		anhDaiDien: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=300&q=80',
		tenCauLacBo: 'CLB Thiện Nguyện',
		ngayThanhLap: '04/11/2021',
		moTa: '<p>CLB tổ chức các chương trình cộng đồng, chiến dịch quyên góp và hoạt động hỗ trợ học sinh vùng khó khăn.</p>',
		chuNhiem: 'Phạm Đức Long',
		hoatDong: true,
	},
];

export const DEFAULT_DON_DANG_KY: DonDangKy[] = [
	{
		id: 'don-01',
		hoTen: 'Đào Mạnh Dũng',
		email: 'dung.b24dccc077@student.ptit.edu.vn',
		sdt: '0987654321',
		gioiTinh: 'Nam',
		diaChi: 'Hà Nội',
		soTruong: 'React, TypeScript, UI cơ bản',
		idCauLacBo: 'clb-01',
		lyDoDangKy: 'Muốn tham gia xây dựng sản phẩm thật và nâng kỹ năng frontend.',
		trangThai: 'Approved',
	},
	{
		id: 'don-02',
		hoTen: 'Lê Khánh Linh',
		email: 'linh.khanh@student.ptit.edu.vn',
		sdt: '0911222333',
		gioiTinh: 'Nữ',
		diaChi: 'Bắc Ninh',
		soTruong: 'Thiết kế poster, viết nội dung',
		idCauLacBo: 'clb-02',
		lyDoDangKy: 'Muốn tham gia tổ chức sự kiện và làm truyền thông cho khoa.',
		trangThai: 'Pending',
	},
	{
		id: 'don-03',
		hoTen: 'Ngô Gia Bảo',
		email: 'bao.ngo@student.ptit.edu.vn',
		sdt: '0909988776',
		gioiTinh: 'Nam',
		diaChi: 'Nam Định',
		soTruong: 'Tổ chức hoạt động, làm việc nhóm',
		idCauLacBo: 'clb-03',
		lyDoDangKy: 'Muốn tham gia hoạt động cộng đồng và hỗ trợ các chương trình thiện nguyện.',
		trangThai: 'Rejected',
		ghiChu: 'CLB đã đủ số lượng thành viên cho đợt hiện tại.',
	},
	{
		id: 'don-04',
		hoTen: 'Phùng Mai Anh',
		email: 'mai.anh@student.ptit.edu.vn',
		sdt: '0977333555',
		gioiTinh: 'Nữ',
		diaChi: 'Hải Phòng',
		soTruong: 'Chỉnh sửa ảnh, làm slide, hỗ trợ truyền thông',
		idCauLacBo: 'clb-02',
		lyDoDangKy: 'Muốn tham gia đội media của khoa để tích lũy kinh nghiệm tổ chức sự kiện.',
		trangThai: 'Approved',
	},
	{
		id: 'don-05',
		hoTen: 'Nguyễn Thu Trang',
		email: 'trang.nguyen@student.ptit.edu.vn',
		sdt: '0966888111',
		gioiTinh: 'Nữ',
		diaChi: 'Thái Bình',
		soTruong: 'HTML, CSS, viết báo cáo',
		idCauLacBo: 'clb-01',
		lyDoDangKy: 'Muốn học cách làm việc nhóm và tham gia dự án web thực tế.',
		trangThai: 'Pending',
	},
];

export const DEFAULT_LICH_SU_THAO_TAC: LichSuThaoTac[] = [
	{
		id: 'ls-01',
		idDonDangKy: 'don-01',
		nguoiThucHien: 'Admin',
		hanhDong: 'Approved',
		thoiGian: '31/03/2026 09:15',
		noiDung: 'Admin đã duyệt đơn của Đào Mạnh Dũng vào CLB Lập Trình Web.',
	},
	{
		id: 'ls-02',
		idDonDangKy: 'don-02',
		nguoiThucHien: 'Admin',
		hanhDong: 'Created',
		thoiGian: '31/03/2026 10:20',
		noiDung: 'Admin đã tạo đơn đăng ký của Lê Khánh Linh vào CLB Truyền Thông Sáng Tạo.',
	},
	{
		id: 'ls-03',
		idDonDangKy: 'don-03',
		nguoiThucHien: 'Admin',
		hanhDong: 'Rejected',
		thoiGian: '31/03/2026 11:05',
		noiDung: 'Admin đã từ chối đơn của Ngô Gia Bảo với lý do: CLB đã đủ số lượng thành viên cho đợt hiện tại.',
	},
];
